### ISSUE TITLE
NWK anlegen Excel-Import

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#13]
Als örtl. Ausbildungsleitung möchte ich eine Excel Tabelle in die Anwendung hochladen, sodass ich problemlos eine große Menge von NWKs anlegen kann.

**Akzeptanzkriterien:**
- [x] Eine Excel Datei kann hochgeladen werden
- [x] NWKs werden entsprechend der Datei angelegt und gespeichert
- [x] ein Feedback wird zurückgegeben ob das Anlegen erfolgreich war
- [x] Bei einem Fehler im Datensatz wird der Import abgebrochen und nichts gespeichert

Zusätzliche Infos zur Implementierung:

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.
```[tasklist]
### Tasks
```
---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by MoonaLiisaa** [comment]
- [ ] Design erstellen
- [ ] Backend Endpoint erstellen (DTO)
- [ ] Backend Service zur Excelverarbeitung erstellen
- [ ] Datenstruktur erstellen (Datenbank)
- [ ] Testaufgaben erstellen (für Usability Tests)
- [ ] Frontendverbindung zum Backend ist vorhanden
- [ ] Frontendvalidierungen erstellen
- [ ] Backendvalidierungen erstellen
- [ ] Frontendoberfläche gem. Design implementieren
- [ ] Fehlerbehandlung Backend

**Comment by TobiasCersowsky** [comment]
https://www.figma.com/file/ZqUDvgys2aicPSzNPUf76a/NWK-anlegen-Excel-Import%2313?type=design&node-id=0%3A1&mode=design&t=kcs9AM8bxcJzkqeP-1
