### ISSUE TITLE
Notizbereich zu NWKs

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#18]
Als örtl. Ausbildungsleitung möchte ich zu jeder NWK Notizen verfassen können, sodass ich Ihre Präferenzen und Fähigkeiten im Blick behalten kann.

**Akzeptanzkriterien:**
- [ ] Es gibt ein Feld zur Eintragung von Notizen
- [ ] Die Notizen werden dauerhaft gespeichert 

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [ ] Ist das Bearbeiten nur auf der NWK Übersicht im Bearbeiten Dialog möglich: ja
- [ ] Wie lang können diese Notizen sein:
  - [ ] Stichpunktartig, teilweise auch mehrere 

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt
