### ISSUE TITLE
Nur eine Mail pro Meldezeitraum pro Ausbilder*in

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#183]
**User Story:**  
Als örtl. Ausbildungsleitung möchte jeder/m Ausbilder*in nur eine Mail pro Meldezeitraum schicken können, damit ich beim Versenden der Mails nicht an alle Ausbilder mehrmals die gleiche Mail versenden kann.  

**Akzeptanzkriterien:**  
- [ ] Jede*r Ausbilder*in kann nur eine Mail pro Meldezeitraum erhalten
- [ ] Gibt es keine*n Aubilder*in mehr an den in diesem Meldezeitraum eine Mail versendet werden kann, wird der Nutzer beim Versuch darüber informiert.
- [ ] Ist ein Fehler beim Versenden an eine*n bestimmte*n Ausbilder*in geschehen, kann an diesen erneut versendet werden.
- [ ] In einem neuen Zeitraum kann an alle wieder eine Mail versendet werden.

**Zusätzliches Infos zur Implementierung:**

---
**Definition of Ready (DoR):**

- [ ] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [ ] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt
