### ISSUE TITLE
Details zu NWKs bei Zuweisung

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#20]
Als örtl. Ausbildungsleitung möchte ich auf der Zuweisungsseite schnell alle vorhandenen Informationen zu einer NWK erhalten können, sodass ich diese bei der Zuweisung berücksichtigen kann.

**Akzeptanzkriterien:**
- [x] Die Informationen einer NWK werden angezeigt
- [x] Die Zuweisungsseite muss dafür nicht verlassen werden

Zusätzliche Infos zur Implementierung:

Fragen für Refinement:
- [x] Welche Informationen sind das?
- [x] Gibt es schon einen Plan auf welche art die Details dargestellt werden sollen
  - [x] Dialog, Hover, "Cardexpansion " etc.

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by LuisEinig** [comment]
Umsetzungsdetails:
Backend call um alle Infos abzurufen

**Comment by andingerMUC** [comment]
Refinement:
Welche Informationen sind das? Vorlesungstage, falls möglich Hinweis auf Berufsschulblöcke, Personalnummer (Herkunft bisher unbekannt; wird zukünftig wichtig), Mailadresse;

**Comment by MoonaLiisaa** [comment]
ToDo: Story wird in zwei Stories aufgeteilt (Personalnummer, bzw. die Einbindung von Fremdsystemen benötigt einen größeren Aufwand und muss separat bedacht werden) @Tuckerle

**Comment by Tuckerle** [comment]
- [ ] Design implementieren
