### ISSUE TITLE
Entfernung der Zuweisung der NWK

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#21]
Ich als örtl. Ausbildungsleitung möchte die Zuweisung einer NWK zu einem Praktikumsplatz wieder entfernen können, sodass ich eine fehlerhafte Zuweisung rückgängig machen kann.

**Akzeptanzkriterien:**
- [x] Die NWK kann aus dem Praktikumsplatz entfernt werden
- [x] Die NWK erscheint danach wieder in der NWK-Zuweisungs-Liste
- [x] Der Praktikumsplatz ist wieder besetzbar
- [x] ein Feedback wird zurückgegeben ob die NWK Entfernt wurde

Fragen für Refinement:
- [x] Soll eine Bestätigung erscheinen, wenn eine NWK von einem PP entfernt wird?

Zusätzliche Infos zur Implementierung:

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by Tuckerle** [comment]
Refinment:
Bestätigung bei Entfernen einer NWK, von PP, erfragen
