### ISSUE TITLE
Übermittlung der Zuweisungstabelle an POR

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#23]
Ich als örtl. Ausbildungsleitung möchte die Zuweisungstabelle direkt ans POR übermitteln können, sodass ich nicht mehr selbst diese Mail verfassen muss.

**Akzeptanzkriterien:**
- [ ] Es wird eine Warnung angezeigt, wenn beim Export Praktikumsplätze, mit Dringlichkeit Zwingend und Dringend, nicht mit einer NWK besetzt sind
- [ ] Es wird eine Warnung angezeigt, wenn beim Export Praktikumsplätze, mit namentlicher Anforderung unbesetzt sind
- [ ] Es wird eine Warnung angezeigt, wenn beim Export NWKs noch nicht einem Praktikumsplatz zugewiesen sind
- [ ] Es wird eine Warnung angezeigt, wenn beim Export NWKs schon mal bei der Stelle waren
- [ ] Zuweisungen werden in eine Tabelle exportiert
- [ ] Tabelle wird per Mail nach einer Bestätigung durch mich an das POR übermittelt

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [ ] Wie sinnvoll ist das Feature überhaupt?
- [ ] Wenn sinnvoll -> soll altes exportieren dadurch überschrieben werden oder beides möglich sein?

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt

---
**Fragen**
- Wir würden die Mail Adresse gerne ändern zu it-m.ausbildung@muenchen.de
