### ISSUE TITLE
Praktikumsstellen Bearbeiten

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#25]
Ich als örtl. Ausbildungsleitung möchte PPs bearbeiten können, sodass ich fehlerhafte oder fehlende Inhalte ausbessern kann.

**Akzeptanzkriterien:**
- [ ] Es gibt eine Möglichkeit eine PP zu bearbeiten
- [ ] Die Änderung wird dauerhaft gespeichert

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [x] Was soll alles bearbeitet werden: Alle Daten die wir aktuell zu einer Stelle speichern
- [x] Meldezeitraum Soll auch geändert werden können
  - [x] Bei Stelle  mit Zuweisung soll der Meldezeitraum nicht geändert werden können
- [x] Generell sollen Stellen auch bearbeitet werden können, wenn schon eine NWK zugewiesen wurde
- [x] Nach erfolgter Zuweisung sollen nur folgende Daten bearbeitet werden können:
  - [x] Ausbilder
  - [x] Mail Adresse
  - [x] Tätigkeit
  - [x] Dienststelle
 
---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt

**Comment by IamPekka058** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Praktikumsplaner-650bff5c552a4616fb4b3a8d/issues/it-at-m/Praktikumsplaner/25?planning-poker) with Zenhub @danielnwz @LuisEinig @Tuckerle @MrSebastian

**Comment by MrSebastian** [comment]
i cannot edit. The success message appears but nothing is changed
