### ISSUE TITLE
Mail-Versand: nicht erfolgte Praktikumszuteilung Ausbilder*innen

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#26]
Ich als örtl. Ausbildungsleitung möchte Mails auch im Falle, dass keine NWK zu einem PP zugewiesen wurde an den Ausbilder verschicken, sodass die Ausbilder auch über eine Nichtbesetzung informiert werden.

**Akzeptanzkriterien:**
- [ ] Mail-Vorlage wird automatisch mit den korrekten Daten befüllt
- [ ] Mail wird nach Bestätigung durch mich versendet

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [ ] Vorlage für Mail fehlt
- [ ] Welche Daten sollen dort drinstehen? 
- [ ] Was wenn Ausbilder*in mehrere Stellen gemeldet hat. Wie unterscheidet man diese, sodass der Ausbilder das gut erkennt? 

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Fragen**
Soll das versenden von mails für einen Meldezeitraum mehrfach möglich sein, dann würden Ausbilder potenziell mehrfach Mails erhalten.
---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt
