### ISSUE TITLE
Löschung von NWKs

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#27]
Ich als örtl. Ausbildungsleitung möchte NWKs löschen können, sodass ich NWKs, welche die nicht mehr für die Stadt arbeiten entfernen kann.

**Akzeptanzkriterien:**
- [ ] Die NWK ist nach der Löschung nicht mehr vorhanden
- [ ] Vor dem Löschen soll eine Bestätigung angefordert werden
- [ ] Es gibt ein Feedback ob meine Löschung erfolgreich war

Zusätzliche Infos zur Implementierung:

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt

**Comment by IamPekka058** [comment]
- [ ] Backendendpoint anlegen
- [ ] Frontendservice anlegen
- [ ] Frontend einpflegen
- [ ] Unittests schreiben

**Comment by IamPekka058** [comment]
Es sind noch Fragen aufgekommen, die geklärt werden sollten:
- Was genau heißt "löschen"? (Auf inaktiv setzen oder wirklich löschen)
- Gibt es Bedingungen zum Löschen? (zb. keine zugewiesene Nwk)
