### ISSUE TITLE
Detailsicht NWKs

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#28]
Ich als örtl. Ausbildungsleitung möchte genauere Informationen über eine NWK erhalten, sodass ich diese besser zuweisen kann.

**Akzeptanzkriterien:**
- [ ] Es kann zur einer NWK eine Detailansicht geöffnet werden
- [ ] Die Detailansicht soll alle Infos über die NWK enthalten

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [ ] Dialog? Extra Seite? Ausklappbar? 
- [ ] Bearbeiten nur dann möglich? Oder weiterhin in der Übersicht bei jeder NWK dieser Button. 
- [ ] Was sind denn genau die Details? (Wochentage, ?)

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt

**Comment by Tuckerle** [comment]
Bietet Stand 23.02. noch keinen Mehrwert und wird deshalb in der Priorisierung nach unten geschoben.
Bei der Implementierung einer Zuweisungshistorie #32 soll diese Story noch einmal betrachtet werden, ob und wie sie dann einen Mehrwert bietet.
