### ISSUE TITLE
Mail-Feedback zu gemeldeten Stellen

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#29]
Als örtl. Ausbilder*in möchte ich nach dem Melden meiner Stelle eine E-Mail mit den Daten der von mir gemeldeten Stelle erhalten, um prüfen zu können ob die Stelle korrekt gemeldet wurde und einen Überblick über die von mir gemeldeten Stellen behalten zu können. 

**Akzeptanzkriterien:**

- [ ] Nach dem Melden der Stelle erhalte ich eine E-Mail
- [ ] Die E-Mail enthält die Daten der von mir zuletzt gemeldeten Stelle
- [ ] Es werden mir auch die Felder angezeigt, bei denen ich keine Angaben gemacht habe

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [ ] Feature überhaupt noch sinnvoll? Übersicht für die jeweilige Ausbilder*in auch direkt in der Anwendung möglich. 

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt
