### ISSUE TITLE
Aufforderungsemail zum Fordern von Praktikumsstellen

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#30]
Als örtl. Ausbildungsleitung möchte ich, dass die Applikation eine Email mit der Aufforderung zur Meldung von Praktikumsstellen versendet wird, sodass die Ausbilder*innen darüber informiert sind, dass sie jetzt Praktikumsplätze melden können.

**Akzeptanzkriterien:**
- [ ] Mail wird versendet an: Abteilungsleitung, Personen, welche innerhalb der letzten 2 Jahre bereits eine Stelle gemeldet haben
- [ ] Mail wird zu Beginn eines Meldezeitraums verschickt

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [ ] Woher kommt die Info wer Abteilungsleitung ist? 
- [ ] Soll das automatisch passieren oder nochmal manuell getriggert werden?
- [ ] Wie sieht diese Mail aus?

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt
