### ISSUE TITLE
NWK Zuweisungshistorie

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#32]
Als örtl. Ausbildungsleitung möchte ich eine Historie über die Zuweisung einer NWK haben, sodass ich sehen kann, bei welchen Abteilungen sie eigentlich nicht mehr eingeteilt werden soll.

**Akzeptanzkriterien:**
- [ ] Historie ist bei den Details zur NWK sichtbar

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [ ] Nur Abteilung? Oder auch genaue Praktikumsstelle? 
- [ ] Soll das bearbeitbar sein?

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt
