### ISSUE TITLE
Filterung der Praktikumsplätze in der Zuteilung

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#35]
Als örtl. Ausbildungsleitung möchte ich eine Filteroption für Praktikumsplätze auf der Zuweisungsseite haben, sodass ich die Menge der zu bearbeitenden Praktikumsplätze auf ein überschaubares Maß reduzieren kann.

**Akzeptanzkriterien:**
- [ ] Es gibt eine Auswahl versch. Filter
- [ ] Bei einer Filterung werden nur die den Filter erfüllenden Praktikumsplätze angezeigt
- [ ] Es ist möglich eine Filterung zurückzunehmen

Zusätzliche Infos zur Implementierung:

Fragen an PO: 
- [ ] Welche Filtermöglichkeiten gibt es:
  - [ ] Studienrichtung
  - [ ] Ausbildungsjahr/Semester
  - [ ] Dringlichkeit
  - [ ] Projektarbeit
- [ ] Soll der Filter solange da sein bis er manuell aufgehoben wird oder wenn man die Seite wechselt wieder weg sein
  - [ ] Filter soll auf dem gleichen Rechner aktiv bleiben bis er aufgehoben wird (solange der Tab offen ist)
- [ ] Es soll möglich sein mehrere Filter zu setzen, diese werden dann UND verknüpft, es werden also nur Ergebnisse angezeigt, die alle Kriterien erfüllen
---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt
